Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2021-09, with the labels that each got.

#249 Fix for incorrect paths in docker image file
  src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
Labels: type: bug, relates-to: graal

#256 Support custom entry points
  src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
  src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
Labels: type: bug

#242 [gradle-plugin] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradlew
Labels: relates-to: build

#258 Add another missing placeholder task
  build.gradle
Labels: type: bug, relates-to: build

#259 Add one more missing placeholder task
  build.gradle
Labels: relates-to: build

#261 Revert changes to release workflow
  .github/workflows/release.yml
Labels: relates-to: build
