Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2021-12, with the labels that each got.

#331 Add the `deduceEnvironment` optimization
  gradle/libs.versions.toml
  samples/aot/basic-app/build.gradle
  samples/aot/with-shadow/build.gradle
  src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java
  src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java
  src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
Labels: relates-to: aot

#336 Fix configuration missing when merging user configuration with defaults
  src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java
Labels: type: bug, relates-to: aot

#341 Upgrade log4j
  build.gradle
  gradle/libs.versions.toml
Labels: relates-to: security

#342 Upgrade to AOT 1.0.0-M3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#345 Upgrade to Micronaut AOT 1.0.0-M4
  gradle/libs.versions.toml
  samples/aot/basic-app/build.gradle
  samples/aot/with-shadow/build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java
  src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java
  src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
Labels: type: dependency-upgrade

#339 [gradle-plugin] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/windows-ci.yml
  .gitignore
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  settings.gradle
Labels: relates-to: build

#350 Upgrade to native build tools 0.9.9
  gradle/libs.versions.toml
  src/docs/asciidoc/index.adoc
Labels: type: dependency-upgrade

#352 Upgrade to Micronaut AOT 1.0.0-M5
  gradle/libs.versions.toml
  src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
Labels: type: dependency-upgrade

#353 Filter out main source set output from optimized run
  src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
Labels: type: bug, relates-to: aot

#354 Make it more convenient to declare AOT plugins
  src/docs/asciidoc/index.adoc
  src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java
  src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java
  src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
Labels: type: improvement, relates-to: aot
