Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2022-11, with the labels that each got.

#580 Fix "run" task in IntelliJ
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
Labels: type: bug

#581 Upgrade to GraalVM native plugin 0.9.17
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#582 Fix CRaC for ubuntu 22.04
  crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
  crac-plugin/src/main/resources/checkpoint.sh
  src/docs/asciidoc/index.adoc
Labels: type: bug

#585 Allow setting a network for the crac checkpoint
  crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCConfiguration.java
  crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
Labels: type: enhancement

#595 Fix custom dockerfile usage
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
Labels: type: bug

#596 Let the user specify a duplicates strategy when building layers
  .github/workflows/graalvm.yml
  docker-plugin/src/main/java/io/micronaut/gradle/docker/tasks/BuildLayersTask.java
  docker-plugin/src/test/groovy/io/micronaut/gradle/BuildLayersSpec.groovy
  src/docs/asciidoc/index.adoc
Labels: type: bug

#597 Move the test resources port file outside the build directory
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
Labels: type: bug

#600 Remove `testNativeImage`
  graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
  graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageTestTaskSpec.groovy
  src/docs/asciidoc/index.adoc
Labels: type: breaking

#602 Upgrade dependencies
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#604 Fix `test` task being out of date with test resources
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy
  gradle/libs.versions.toml
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
Labels: type: bug
