Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2022-02, with the labels that each got.

#387 Upgrade to Native Build Tools 0.9.10
  .github/workflows/graalvm.yml
  gradle/libs.versions.toml
  src/docs/asciidoc/index.adoc
  src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  src/test/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
  src/test/groovy/io/micronaut/gradle/MicronautGraalPluginSpec.groovy
  src/test/groovy/io/micronaut/gradle/NativeImageTaskSpec.groovy
Labels: type: dependency-upgrade

#346 [gradle-plugin] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  .gitignore
  MAINTAINING.md
  SECURITY.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#388 Make sure `run` tasks are always executed
  src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
  src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
Labels: type: bug
