Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2022-03, with the labels that each got.

#398 Use argument file to call AOT tasks
  aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
Labels: type: bug, relates-to: aot

#403 Support spaces in paths in argfile
  aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
  minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
Labels: type: bug

#407 Fix service files not merged with shadow plugin
  functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy
  gradle/libs.versions.toml
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
Labels: type: bug

#408 Upgrade to Micronaut AOT 1.0.0
  aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#412 fix: shadowJar.mergeServiceFiles also for library
  functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/ShadowPluginSupport.java
Labels: type: bug

#389 Upgrade to GraalVM 22.0.0.2 by default
  .github/workflows/windows-ci.yml
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
Labels: type: dependency-upgrade

#415 Rework how the default runtime class is set for Lambda
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
  graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
Labels: type: bug, relates-to: graal, relates-to: docker

#422 Fix docker plugin assuming graal plugin applied
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/FullMicronautRuntimeSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/AbstractAOTPluginSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractEagerConfiguringFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/graalvm/MicronautGraalPluginSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/KotlinLibraryFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/shadow/ShadowJarSpec.groovy
Labels: type: bug

#425 Upgrade to Micronaut AOT 1.0.1
  aot-plugin/build.gradle
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  aot-plugin/src/templates/java/io/micronaut/gradle/aot/Versions.java
  buildSrc/src/main/groovy/io.micronaut.internal.build.processed-sources.gradle
  buildSrc/src/main/groovy/io/micronaut/internal/build/sourcegen/SimpleSourceProcessor.java
  functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractFunctionalTest.groovy
  gradle/libs.versions.toml
  src/docs/asciidoc/index.adoc
Labels: type: dependency-upgrade

#390 [gradle-plugin] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  .github/workflows/windows-ci.yml
  build.gradle
  config/checkstyle/checkstyle.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build
