Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2022-09, with the labels that each got.

#530 Upgrade default GraalVM version to 22.2
  .github/workflows/sonarqube.yml
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
Labels: type: dependency-upgrade

#529 Fix test-resources directory not created when running clean build
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
Labels: type: bug

#535 doc: correct native-build-tools-version
  src/docs/asciidoc/index.adoc
Labels: type: docs

#532 Bump minimal requirements to Java 17
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  .github/workflows/windows-ci.yml
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/model/MicronautDockerImage.java
  docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/FunctionsMicronautAOTSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/ShadowMicronautAOTSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/graalvm/MicronautGraalPluginSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy
  graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
  graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageMultiProjectSpec.groovy
  graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageTaskSpec.groovy
  graalvm-plugin/src/test/groovy/io/micronaut/gradle/NativeImageTestTaskSpec.groovy
  samples/aot/aws-function/build.gradle
  samples/aot/basic-app/build.gradle
  samples/aot/with-shadow/build.gradle
  src/docs/asciidoc/index.adoc
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
Labels: type: breaking, type: improvement

#545 improve Crac Tasks Documentation
  src/docs/asciidoc/index.adoc
Labels: type: docs

#555 Workaround BouncyCastleFeature accessing GraalVM internal APIs
  functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractEagerConfiguringFunctionalTest.groovy
  graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
Labels: type: bug

#558 Upgrade native plugin
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  gradle/libs.versions.toml
  minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
Labels: type: dependency-upgrade
