Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2022-06, with the labels that each got.

#475 Fix typo in property name
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
Labels: type: bug

#471 Pull GraalVM JDK based on system architecture
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
  src/docs/asciidoc/index.adoc
Labels: type: enhancement

#478 Add test resources plugin
  functional-tests/build.gradle
  gradle-plugin/build.gradle
  gradle-plugin/src/main/java/io/micronaut/gradle/MicronautLibraryPlugin.java
  gradle/libs.versions.toml
  minimal-plugin/build.gradle
  minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
  samples/aot/basic-app/build.gradle
  samples/test-resources/data-mysql/build.gradle
  samples/test-resources/data-mysql/gradle.properties
  samples/test-resources/data-mysql/settings.gradle
  samples/test-resources/data-mysql/src/main/java/demo/Application.java
  samples/test-resources/data-mysql/src/main/java/demo/Book.java
  samples/test-resources/data-mysql/src/main/java/demo/BookController.java
  samples/test-resources/data-mysql/src/main/java/demo/BookRepository.java
  samples/test-resources/data-mysql/src/main/java/demo/User.java
  samples/test-resources/data-mysql/src/main/java/demo/UserController.java
  samples/test-resources/data-mysql/src/main/java/demo/UserRepository.java
  samples/test-resources/data-mysql/src/main/resources/application.yml
  samples/test-resources/data-mysql/src/main/resources/logback.xml
  samples/test-resources/data-mysql/src/test/java/demo/DemoTest.java
  settings.gradle
  test-resources-plugin/build.gradle
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StopTestResourcesService.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/TestResourcesConfiguration.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
Labels: type: improvement

#482 Move configuration to `afterEvaluate`
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
Labels: type: bug

#484 Add custom `testResources` source set
  samples/test-resources/custom-test-resource/build.gradle
  samples/test-resources/custom-test-resource/gradle.properties
  samples/test-resources/custom-test-resource/settings.gradle
  samples/test-resources/custom-test-resource/src/main/java/demo/Application.java
  samples/test-resources/custom-test-resource/src/main/resources/application.yml
  samples/test-resources/custom-test-resource/src/main/resources/logback.xml
  samples/test-resources/custom-test-resource/src/test/java/demo/DemoTest.java
  samples/test-resources/custom-test-resource/src/testResources/java/demo/GreetingTestResource.java
  samples/test-resources/custom-test-resource/src/testResources/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/CustomTestResourcePluginSpec.groovy
Labels: type: improvement

#486 Add test resources documentation
  samples/test-resources/custom-test-resource/src/test/java/demo/DemoTest.java
  samples/test-resources/multiproject/app1/build.gradle
  samples/test-resources/multiproject/app2/build.gradle
  samples/test-resources/multiproject/app3/build.gradle
  src/docs/asciidoc/index.adoc
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesConsumerPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/TestResourcesConsumerConfiguration.java
Labels: type: docs

#487 Tweak test resources service startup options
  gradle/libs.versions.toml
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java
Labels: type: improvement

#490 Integrate with native and AOT
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/AbstractTestResourcesSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy
  minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java
  samples/test-resources/data-mysql/build.gradle
  test-resources-plugin/build.gradle
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/TestResourcesConfiguration.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesAOT.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
Labels: type: improvement

#492 Upgrade to Micronaut Test Resources 1.0.0-M4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
