Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2022-04, with the labels that each got.

#430 Upgrade to Micronaut AOT 1.0.2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#434 fix: Adds LAMBDA_JAVA and LAMBDA_PROVIDED runtimes
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  functional-tests/src/test/groovy/io/micronaut/gradle/RuntimeDependenciesSpec.groovy
  graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/Dependencies.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntime.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java
Labels: type: bug

#437 Upgrade to Micronaut AOT 1.0.3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#439 Use `api` dependencies between plugins
  aot-plugin/build.gradle
  docker-plugin/build.gradle
  graalvm-plugin/build.gradle
  gradle-plugin/build.gradle
Labels: type: bug

#447 Upgrade to Micronaut AOT 1.1.0
  aot-plugin/src/main/java/io/micronaut/gradle/aot/AOTOptimizations.java
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAOTConfigWriterTask.java
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  aot-plugin/src/main/java/io/micronaut/gradle/aot/NettyOptimizations.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/FunctionsMicronautAOTSpec.groovy
  gradle/libs.versions.toml
  samples/aot/basic-app/build.gradle
  settings.gradle
  src/docs/asciidoc/index.adoc
Labels: type: dependency-upgrade

#448 Upgrade to GraalVM 22.1
  .github/workflows/graalvm.yml
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
Labels: type: dependency-upgrade

#449 Upgrade build tools to 5.3.4
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  buildSrc/src/main/groovy/io.micronaut.internal.build.testing.gradle
  settings.gradle
Labels: relates-to: build
