Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2023-05, with the labels that each got.

#714 graalvm native-image docker replace ol7 with ol8
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
Labels: relates-to: graal

#718 Bump to Native Build Tools 0.9.22
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#719 Fix test resources version check
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/MicronautTestResourcesPluginTest.groovy
Labels: type: bug

#727 Upgrade to Test Resources 2.0.0-M8
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
