Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2023-02, with the labels that each got.

#634 Add KSP support and re-enable Kotlin tests
  buildSrc/src/main/groovy/io.micronaut.internal.build.functional-testing.gradle
  functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/Kotest5FunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/KotlinLibraryFunctionalTest.groovy
  gradle/libs.versions.toml
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautTestRuntime.java
  minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java
  minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
Labels: type: enhancement

#620 Fix test/run task being up-to-date
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/CustomTestResourcePluginSpec.groovy
Labels: type: bug

#640 Fix compatibility with Gradle 8
  buildSrc/src/main/groovy/io.micronaut.internal.build.gradle-plugin.gradle
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
Labels: type: bug

#638 Enable GraalVM metadata repository
  aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/tasks/DockerResourceConfigDirectoryNamer.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/tasks/PrepareDockerContext.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  graalvm-plugin/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java
  gradle-plugin/src/test/groovy/io/micronaut/gradle/MicronautLibraryPluginSpec.groovy
  minimal-plugin/src/test/groovy/io/micronaut/gradle/MicronautMinimalLibraryPluginSpec.groovy
Labels: type: improvement

#644 Fix regression in test framework usage
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautTestRuntime.java
Labels: type: bug

#650 Fix compatibility with Gradle 8
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
Labels: type: bug, relates-to: docker

#654 Fix integration with GraalVM repository
  .github/workflows/graalvm.yml
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracBuildTaskSpec.groovy
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy
  samples/aot/aws-function/src/main/resources/logback.xml
  samples/test-resources/custom-test-resource/src/main/resources/logback.xml
  samples/test-resources/data-mysql/build.gradle
  samples/test-resources/data-mysql/src/main/resources/logback.xml
  samples/test-resources/isolated-multiproject/app1/src/main/resources/logback.xml
  samples/test-resources/isolated-multiproject/app2/src/main/resources/logback.xml
  samples/test-resources/multiproject/app1/src/main/resources/logback.xml
  samples/test-resources/multiproject/app2/src/main/resources/logback.xml
Labels: type: bug
