Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2023-09, with the labels that each got.

#814 Use optimized jar for building the optimized native binary
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/BasicMicronautAOTSpec.groovy
  samples/aot/basic-app/build.gradle
  samples/aot/basic-app/src/main/resources/logback.xml
Labels: type: bug

#816 Upgrade Micronaut AOT
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#822 Fix test resources flag ignored when true
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java
Labels: type: bug

#823 Upgrade Native Build Tools to 0.9.26
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
  gradle/libs.versions.toml
  minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
Labels: type: dependency-upgrade

#824 Fix error when AOT + test resources are applied with library plugin
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotSpec.groovy
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesAOT.java
Labels: type: bug

#828 Fix CRaC JDK download in docker container
  crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java
  crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy
Labels: type: bug

#830 Use an Arm compatible base image for Arm dockerBuildNative
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  src/docs/asciidoc/index.adoc
Labels: relates-to: graal

#844 Make configurable fields public
  aot-plugin/src/main/java/io/micronaut/gradle/aot/AbstractMicronautAotCliTask.java
  buildSrc/src/main/groovy/io/micronaut/internal/build/sourcegen/SimpleSourceProcessor.java
  minimal-plugin/src/main/java/io/micronaut/gradle/ApplicationClasspathInspector.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StartTestResourcesService.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/StopTestResourcesService.java
Labels: type: bug
