Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2023-04, with the labels that each got.

#684 Fix micronaut.processing.group option
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
Labels: type: bug

#685 Fix duplicate entries on classpath
  aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotAndGraalVMSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithGraalVMSpec.groovy
  minimal-plugin/src/main/java/io/micronaut/gradle/AttributeUtils.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
  src/docs/asciidoc/index.adoc
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesAOT.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/internal/TestResourcesGraalVM.java
Labels: type: bug

#692 Revert to amazon linux 2
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
Labels: type: bug

#694 Add a plugin to import the Micronaut Platform catalog
  build.gradle
  buildSrc/build.gradle
  functional-tests/build.gradle
  functional-tests/src/test/groovy/io/micronaut/gradle/fixtures/AbstractFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/settings/VersionOverrideFunctionalTest.groovy
  gradle/libs.versions.toml
  minimal-plugin/src/main/java/io/micronaut/gradle/Dependencies.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautMinimalApplicationPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java
  minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java
  minimal-plugin/src/main/java/io/micronaut/gradle/internal/AutomaticDependency.java
  minimal-plugin/src/main/java/io/micronaut/gradle/internal/ConfigurableVersionProperty.java
  minimal-plugin/src/main/java/io/micronaut/gradle/internal/Dependencies.java
  minimal-plugin/src/test/groovy/io/micronaut/gradle/MicronautMinimalApplicationPluginSpec.groovy
  minimal-plugin/src/testFixtures/groovy/io/micronaut/gradle/AbstractGradleBuildSpec.groovy
  platform-catalog-plugin/build.gradle
  platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/LenientVersionCatalogParser.java
  platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/Library.java
  platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/MicronautCatalogSettingsPlugin.java
  platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/RichVersion.java
  platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/RichVersionParser.java
  platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/VersionCatalogTomlModel.java
  platform-catalog-plugin/src/main/java/io/micronaut/gradle/catalog/VersionModel.java
  platform-catalog-plugin/src/test/groovy/io/micronaut/gradle/settings/CatalogPluginFunctionalTest.groovy
  settings.gradle
  src/docs/asciidoc/index.adoc
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesConsumerPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
Labels: type: improvement

#699 Upgrade to Platform M1
  gradle/libs.versions.toml
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
  test-resources-plugin/src/test/groovy/io/micronaut/gradle/testresources/ApplicationTestResourcesPluginSpec.groovy
Labels: type: dependency-upgrade

#701 Add an option to not automatically add BOM
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautComponentPlugin.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautExtension.java
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
  minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java
  src/docs/asciidoc/index.adoc
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesConsumerPlugin.java
  test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java
Labels: type: improvement

#703 GraalVM 22.3.2
  .github/workflows/sonarqube.yml
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
  settings.gradle
  src/docs/asciidoc/index.adoc
Labels: type: dependency-upgrade, relates-to: graal

#705 Replace deprecated set-output command
  .github/workflows/release.yml
Labels: relates-to: build
