Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2023-03, with the labels that each got.

#656 Upgrade to Micronaut Test Resources 1.2.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#662 Upgrade Micronaut Test Resources
  .github/workflows/release-notes.yml
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#665 Document the network configuration for CRaC
  src/docs/asciidoc/index.adoc
Labels: type: docs

#666 Fix CRaC plugin for Gradle 8
  crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
Labels: type: bug

#670 Upgrade to Docker plugin v9
  crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java
  crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerPlugin.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  gradle/libs.versions.toml
  settings.gradle
Labels: type: dependency-upgrade

#671 Introduce option to customize generated docker files
  docker-plugin/src/main/java/io/micronaut/gradle/docker/DockerBuildOptions.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/DockerfileEditor.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/editor/DefaultEditor.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/editor/Editor.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/editor/FingerprintingEditor.java
  docker-plugin/src/test/groovy/io/micronaut/gradle/docker/editor/DefaultEditorTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  src/docs/asciidoc/index.adoc
Labels: type: bug

#672 Fix native lambda builds within Docker
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/lambda/LambdaNativeImageSpec.groovy
Labels: type: bug

#677 Clarify documentation
  README.md
  build.gradle
  src/docs/asciidoc/index.adoc
Labels: type: docs

#676 Build fixes
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/sonarqube.yml
  buildSrc/src/main/groovy/io.micronaut.internal.build.functional-testing.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.build.gradle-plugin.gradle
  buildSrc/src/main/groovy/io.micronaut.internal.build.testing.gradle
  crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
  docker-plugin/src/test/groovy/io/micronaut/gradle/BuildLayersSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/Kotest5FunctionalTest.groovy
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#679 Copy the customized CRaC dockerfiles if they exist in the root
  crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java
  crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCFinalDockerfile.java
  crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
  crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy
Labels: type: bug
