Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2024-03, with the labels that each got.

#948 bug: copy layers into final crac image
  crac-plugin/src/main/java/io/micronaut/gradle/crac/MicronautCRaCPlugin.java
  crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracBuildTaskSpec.groovy
Labels: type: bug

#958 Document the jdkVersion property for dockerfileNative
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  src/docs/asciidoc/index.adoc
Labels: type: docs

#968 bug: Fix the Azul API url again
  crac-plugin/src/main/java/io/micronaut/gradle/crac/CRaCCheckpointDockerfile.java
  crac-plugin/src/test/groovy/io/micronaut/gradle/crac/CracCustomizationSpec.groovy
Labels: type: bug

#951 Update libs.versions.toml
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#975 Add documentation around kotlin codegen support
  src/docs/asciidoc/index.adoc
Labels: type: docs
