Repository micronaut-projects/micronaut-gradle-plugin, pull requests merged in 2024-04, with the labels that each got.

#977 Upgrade to Micronaut AOT 2.3.0
  gradle/libs.versions.toml
Labels: type: bug, relates-to: graal, relates-to: aot

#979 fix oraclecloud functions
  docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java
  docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java
  docker-plugin/src/test/groovy/io/micronaut/gradle/DockerBuildTaskSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/aot/MicronautAOTDockerSpec.groovy
  functional-tests/src/test/groovy/io/micronaut/gradle/docker/DockerNativeFunctionalTest.groovy
  src/docs/asciidoc/index.adoc
Labels: type: bug

#986 Mark kotlinProcessors as unresolvable
  minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java
Labels: type: bug, lang: kotlin
